apiVersion: apps/v1
kind: Deployment
metadata:
  name: squirreldb
spec:
  minReadySeconds: 60
  template:
    spec:
      containers:
      - name: squirreldb
        image: bleemeo/squirreldb:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 9201
        envFrom:
        - configMapRef:
            name: squirreldb-config
        readinessProbe:
          httpGet:
            path: /ready
            port: 9201
        lifecycle:
          preStop:
            exec:
              command: ["sleep", "15"]
        resources:
          requests:
            cpu: "0.25"
            memory: 400Mi
          limits:
            cpu: "0.5"
            memory: 1Gi
