commonLabels:
  app: squirreldb

configMapGenerator:
- name: squirreldb-config
  literals:
  - SQUIRRELDB_CASSANDRA_ADDRESSES=cassandra
  - SQUIRRELDB_REDIS_ADDRESSES=redis:6379
  - SQUIRRELDB_LOG_DISABLE_COLOR="true"

resources:
- deployment.yaml
- service.yaml
